# Generated by Django 2.2.1 on 2019-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='blog',
        ),
    ]
