# Generated by Django 2.2.1 on 2019-05-30 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190529_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 16, 56, 23, 377320), verbose_name='date published'),
        ),
    ]
