# Generated by Django 2.2.1 on 2019-06-01 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190601_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 14, 43, 54, 690402), verbose_name='date published'),
        ),
    ]
