# Generated by Django 2.2.1 on 2019-06-01 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20190601_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 15, 30, 2, 392211), verbose_name='date published'),
        ),
    ]
