# Generated by Django 2.2.1 on 2019-06-01 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20190601_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 16, 11, 58, 741026), verbose_name='date published'),
        ),
    ]
