# Generated by Django 2.2.1 on 2019-06-01 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20190601_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 17, 0, 14, 40161), verbose_name='date published'),
        ),
    ]
