# Generated by Django 2.2.1 on 2019-06-01 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_auto_20190601_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 17, 3, 9, 451264), verbose_name='date published'),
        ),
    ]
