# Generated by Django 2.2.1 on 2019-06-02 11:32

import colorful.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20190602_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='back',
            field=colorful.fields.RGBColorField(colors=['#003cb3', '#ff1a1a', '#00e600'], default='#003cb3'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 17, 2, 37, 333963), verbose_name='date published'),
        ),
    ]
