# Generated by Django 2.2.1 on 2019-06-02 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20190602_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 17, 21, 29, 723652), verbose_name='date published'),
        ),
    ]
