# Generated by Django 2.2.1 on 2019-06-02 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_auto_20190602_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 8, 25, 415006, tzinfo=utc), verbose_name='date published'),
        ),
    ]
