# Generated by Django 2.2.1 on 2019-06-02 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_auto_20190602_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 10, 2, 309038, tzinfo=utc), verbose_name='date published'),
        ),
    ]
