# Generated by Django 2.2.1 on 2019-06-02 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0031_auto_20190602_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 21, 44, 6, 274503), verbose_name='date published'),
        ),
    ]
