# Generated by Django 2.2.1 on 2019-06-02 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_auto_20190602_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 23, 32, 11, 578103), verbose_name='date published'),
        ),
    ]
