# Generated by Django 2.2.1 on 2019-06-02 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_auto_20190603_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 0, 27, 4, 869293), verbose_name='date published'),
        ),
    ]
