# Generated by Django 2.2.1 on 2019-06-03 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_auto_20190603_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 14, 37, 36, 803383), verbose_name='date published'),
        ),
    ]
