# Generated by Django 2.2.1 on 2019-06-03 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0043_auto_20190603_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 20, 54, 51, 272564), verbose_name='date published'),
        ),
    ]
