# Generated by Django 2.2.1 on 2019-06-03 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0046_auto_20190603_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 21, 16, 36, 591166), verbose_name='date published'),
        ),
    ]
