# Generated by Django 2.2.1 on 2019-06-04 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0053_auto_20190603_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 12, 21, 30, 706939), verbose_name='date published'),
        ),
    ]
