# Generated by Django 2.2.1 on 2019-06-04 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0061_auto_20190604_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 20, 31, 12, 280938)),
        ),
    ]
