# Generated by Django 2.2.1 on 2019-06-04 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0065_auto_20190604_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 21, 14, 35, 995209)),
        ),
    ]
