# Generated by Django 2.2.1 on 2019-06-04 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0066_auto_20190604_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 21, 16, 43, 13120)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
