# Generated by Django 2.2.1 on 2019-06-04 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0067_auto_20190604_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 21, 20, 2, 441566)),
        ),
    ]
