# Generated by Django 2.2.1 on 2019-06-05 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0073_auto_20190605_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 11, 43, 8, 65207)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
