# Generated by Django 2.2.1 on 2019-06-05 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0074_auto_20190605_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 11, 51, 19, 687154)),
        ),
    ]
