# Generated by Django 2.2.1 on 2019-06-05 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0075_auto_20190605_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 11, 54, 17, 64570)),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
