# Generated by Django 2.2.1 on 2019-06-05 16:25

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0082_auto_20190605_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 21, 55, 32, 453560)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
