# Generated by Django 2.2.3 on 2019-08-08 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0083_auto_20190605_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 19, 43, 27, 663975)),
        ),
    ]
