# Generated by Django 3.0.4 on 2020-03-25 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0084_auto_20190808_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 23, 13, 16, 72221)),
        ),
    ]
